-- Schema do Portal de Pedidos B2B.
-- Compativel com H2 (MODE=PostgreSQL) e PostgreSQL.
DROP TABLE IF EXISTS comprovante;
DROP TABLE IF EXISTS item_pedido;
DROP TABLE IF EXISTS pedido;
DROP TABLE IF EXISTS produto;
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS cliente;

CREATE TABLE cliente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social    VARCHAR(255) NOT NULL,
    cnpj            VARCHAR(32),
    email           VARCHAR(255),
    dados_pagamento VARCHAR(512)
);

CREATE TABLE usuario (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    senha      VARCHAR(255) NOT NULL,
    role       VARCHAR(32)  NOT NULL,
    cliente_id BIGINT
);

CREATE TABLE produto (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000),
    preco     NUMERIC(12,2) NOT NULL,
    estoque   INTEGER
);

CREATE TABLE pedido (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id   BIGINT NOT NULL,
    status       VARCHAR(32) NOT NULL,
    total        NUMERIC(12,2),
    data_criacao TIMESTAMP
);

CREATE TABLE item_pedido (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT,
    produto_id     BIGINT,
    produto_nome   VARCHAR(255),
    quantidade     INTEGER,
    preco_unitario NUMERIC(12,2)
);

CREATE TABLE comprovante (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id    BIGINT,
    nome_arquivo VARCHAR(512),
    caminho      VARCHAR(1024),
    content_type VARCHAR(128),
    tamanho      BIGINT
);
